try {
  Exception.raise
} catch { e ->
  e
}

